name: adcircpy
channels:
  - conda-forge
dependencies:
  - bs4
  - fiona
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pyproj>=2.6
  - requests
  - shapely
  - pip:
      - adcircpy==1.0.12
      - coverage
      - flake8
      - nemspy>=0.4.4
      - nose
      - requests_futures
