name: ensemble_perturbation
channels:
  - conda-forge
  - defaults
dependencies:
  - bs4
  - fiona
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pyproj>=2.6
  - python==3.7.9
  - requests
  - shapely
  - pip:
      - adcircpy>=1.0.12
      - dunamai
      - flake8
      - nemspy>=0.5.2
      - pytest
      - pytest-cov
      - requests_futures
